In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 8
fig_height = 6
fig_format = 'retina'
fig_dpi = 300
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"

  # IPython 7.14 deprecated set_matplotlib_formats from IPython
  try:
    from matplotlib_inline.backend_inline import set_matplotlib_formats
  except ImportError:
    # Fall back to deprecated location for older IPython versions
    from IPython.display import set_matplotlib_formats
    
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'QzpcVXNlcnNcc3NpbmdoXE9uZURyaXZlIC0gTGlldHV2b3MgYmFua2FzXERlc2t0b3BcUGFwZXJzX3RvX3dyaXRlXGJvb2tzXG5vdGVzLWVjb25vbWV0cmljc1xjaGFwdGVycw=='
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\importlib\\_bootstrap.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\importlib\\_bootstrap_external.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\zipimport.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\codecs.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\encodings\\aliases.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\encodings\\__init__.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\encodings\\utf_8.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-datascience\\Lib\\encodings\\cp1257.py": 1760026615.0, "C:\\Users\\ssingh\\AppData\\Local\\miniconda3\\envs\\lecture-d

In [2]:
import numpy as np

# Create vectors
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vector operations
print(f"x + y = {x + y}")
print(f"3*x = {3*x}")
print(f"Inner product: {np.dot(x, y)}")
print(f"Norm of x: {np.linalg.norm(x)}")

x + y = [5 7 9]
3*x = [3 6 9]
Inner product: 32
Norm of x: 3.7416573867739413


In [3]:
# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = A @ B  # or np.dot(A, B)
print(f"A @ B =\n{C}")

# Element-wise multiplication (Hadamard product)
D = A * B
print(f"\nA * B (element-wise) =\n{D}")

A @ B =
[[19 22]
 [43 50]]

A * B (element-wise) =
[[ 5 12]
 [21 32]]


In [4]:
# Symmetric matrix
A = np.array([[4, 2], [2, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

# Verify: A*v = lambda*v
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]
print(f"\nVerification: A*v1 = {A @ v1}")
print(f"lambda1*v1 = {lambda1 * v1}")

Eigenvalues: [5.56155281 1.43844719]
Eigenvectors:
[[ 0.78820544 -0.61541221]
 [ 0.61541221  0.78820544]]

Verification: A*v1 = [4.38364617 3.4226475 ]
lambda1*v1 = [4.38364617 3.4226475 ]


In [5]:
# SVD decomposition
A = np.array([[1, 2, 3], [4, 5, 6]])
U, s, Vt = np.linalg.svd(A)

print(f"U shape: {U.shape}")
print(f"Singular values: {s}")
print(f"Vt shape: {Vt.shape}")

# Reconstruct A
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, s)
A_reconstructed = U @ Sigma @ Vt
print(f"\nReconstructed A:\n{A_reconstructed}")

U shape: (2, 2)
Singular values: [9.508032   0.77286964]
Vt shape: (3, 3)

Reconstructed A:
[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# Generate design matrix
np.random.seed(42)
n, k = 100, 3
X = np.random.randn(n, k)

# Compute projection matrix
P = X @ np.linalg.inv(X.T @ X) @ X.T

# Verify idempotence: P^2 = P
print(f"||P^2 - P|| = {np.linalg.norm(P @ P - P):.2e}")

# Verify symmetry: P = P^T
print(f"||P - P^T|| = {np.linalg.norm(P - P.T):.2e}")

||P^2 - P|| = 7.03e-16


||P - P^T|| = 2.54e-16
